export const TIME_INTERVALS: { [key: string]: number } = {
    second: 1000,
    minute: 60000,
    hour: 3600000,
    day: 86400000
};
TIME_INTERVALS.minute5 = TIME_INTERVALS.minute * 5;
TIME_INTERVALS.minute10 = TIME_INTERVALS.minute * 10;
TIME_INTERVALS.minute15 = TIME_INTERVALS.minute * 15;
TIME_INTERVALS.minute30 = TIME_INTERVALS.minute * 30;
TIME_INTERVALS.hour2 = TIME_INTERVALS.hour * 2;
TIME_INTERVALS.hour3 = TIME_INTERVALS.hour * 3;
TIME_INTERVALS.hour6 = TIME_INTERVALS.hour * 6;
TIME_INTERVALS.hour12 = TIME_INTERVALS.hour * 12;
TIME_INTERVALS.day2 = TIME_INTERVALS.day * 2;
TIME_INTERVALS.day3 = TIME_INTERVALS.day * 3;
TIME_INTERVALS.day7 = TIME_INTERVALS.day * 7;
TIME_INTERVALS.month = TIME_INTERVALS.day * 30;
TIME_INTERVALS.year = TIME_INTERVALS.day * 365;
TIME_INTERVALS.decade = TIME_INTERVALS.year * 10;
